version: '3.7'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: CV7IyyaCde4245v8yOYcXXPbYk5udxvJH4AzCaL1Ud2s=
      POSTGRES_DB: acmefit
    ports:
      - "5432:5432"
